# This is a basic workflow to help you get started with Actions

name: Run Python Tests with Unittest

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: develop
  pull_request:
    branches: develop

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  test:
    name: Test - Backend tests
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      JWT_SECRET_KEY: 'JXQD9iTYBhTOtFUfQvQwe8v4EQR1tSlKZ8f3YmdMkLE='
      MONGO_DB_PASSWORD: ""
      MONGO_DB_HOST: 'mongodb://127.0.0.1:27017'

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.4.0

      # Runs a single command using the runners shell
      - name: Install Python 3
        uses: actions/setup-python@v2.2.2
        with: 
          python-version: 3.8

      # Runs a set of commands using the runners shell
      - name: Install Python Packages
        run: |
          cd flask
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: create .env and JWT_SCRET_KEY
        run: |
          cd flask
          touch .env
          echo "JWT_SECRET_KEY='sdofuhgpohn,pofjmijdsmofitporijdpjdfùpogjdi54686'" > .env
          echo "MONGO_DB_PASSWORD=" > .env
          echo "MONGO_DB_HOST='mongodb://127.0.0.1:27017'" > .env

      - name: Launch flask developpment server
        run: |
          cd flask
          flask run &
          
      - name: Python Unit Test
        run: |
          cd flask
          python -m unittest discover tests

  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.4
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build NginX docker image
        run: docker build ./nginx -t ${{ secrets.DOCKER_REPO_NGINX }}
      - name: Publish NginX docker image
        run: docker push ${{ secrets.DOCKER_REPO_NGINX }}

      - name: Build MongoDB docker image
        run: docker build ./mongodb -t ${{ secrets.DOCKER_REPO_MONGODB }}
      - name: Publish MongoDB docker image
        run: docker push ${{ secrets.DOCKER_REPO_MONGODB }}

      - name: Build Flask docker image
        run: docker build ./flask -t ${{ secrets.DOCKER_REPO_FLASK }}
      - name: Publish Flask docker image
        run: docker push ${{ secrets.DOCKER_REPO_FLASK }}

  redeploy:
    name: Redeploy webhook call
    runs-on: ubuntu-latest
    needs: [docker]
    steps:
      - name: Deploy docker container webhook
        uses: joelwmale/webhook-action@master
        env:
          WEBHOOK_URL: ${{ secrets.DEPLOY_WEBHOOK_URL  }}
          data: "{ 'myField': 'myFieldValue'}"
